### Example usage of one_hot_encode() and shuffle_data()

In [21]:
#testing one_hot_encode from data_loader.py
from data_loader import one_hot_encode, shuffle_data

import numpy as np
matrix = one_hot_encode(np.random.randint(1, 11, size=1), 10)
print("vector:", matrix)

shuffle_data(matrix, np.array([9]))

vector: [[0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


(array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]], dtype=float32), array([9]))

### Exmpale of data_load from .img to vector
Goes into data directory loops through images and transforms them them from a 28x28 matrix into 


In [25]:
from data_loader import load_images_from_folder

load_images_from_folder('data/Reduced_MNIST_Data/Reduced_Trainging_data')


(array([[0.01176471, 0.        , 0.03137255, ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.00392157, 0.        , 0.01176471, ..., 0.        , 0.        ,
         0.        ],
        ...,
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ],
        [0.        , 0.        , 0.        , ..., 0.        , 0.        ,
         0.        ]], dtype=float32),
 array([0, 0, 0, ..., 9, 9, 9]))

### Displaying a raw model

In [6]:
from numpy import load

data = load('models/kaggle_mnist_full.npz')
lst = data.files
for item in lst:

    print(item)
    print(data[item])


learning_rate
[0.000625]
grad_clip_value
[5.]
weight_decay
[1.e-04]
num_layers
[4]
w_0
[[ 0.02515823 -0.00675753  0.0325144  ...  0.05123261 -0.07525576
  -0.02376628]
 [ 0.06340586 -0.03527519  0.02251178 ... -0.04140359  0.01344816
  -0.00183817]
 [-0.01155557 -0.04534511 -0.02891986 ... -0.03525973 -0.00157524
   0.08871194]
 ...
 [-0.03449691 -0.05603703 -0.0431103  ...  0.05764939  0.05882816
  -0.02961164]
 [ 0.00144014  0.01852918 -0.04942425 ... -0.06639216  0.0589985
   0.07517917]
 [-0.06641531 -0.00745052  0.04074965 ... -0.08986856  0.02345931
   0.05311754]]
b_0
[[ 0.02430793 -0.00422853  0.01879867  0.0136947   0.00058463  0.01908068
   0.07433966 -0.02707293  0.00525501 -0.01900467  0.00960945 -0.00272555
   0.00766575 -0.02948339  0.02040309  0.02470942  0.06260729  0.0179873
  -0.0238159   0.02882786  0.00999931  0.0034233   0.07449104 -0.00652787
  -0.03657164 -0.00056606  0.00276155  0.0194351   0.01335309  0.02200978
   0.06207871  0.05025468 -0.0214444  -0.01092127

In [ ]:
import numpy as np
def relu(z):
    return np.maximum(0, z)

def sigmoid(z):
    return 1 / (1 + np.exp(-z))

print(sigmoid(np.array([1,2,3,4,5])))